# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Codecov: https://github.com/codecov/example-r


language: R
cache:
  packages: true
env:
  global:
    - _R_CHECK_SYSTEM_CLOCK_=false
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
